### PR TITLE
#3 add release related workflows

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #3 
 - https://github.com/interscript/interscript/commit/5af53a0a21e209766316ffb6295b8b1de0cd1e4e

GHA part is done, but deployment by itself not implemented yet https://github.com/interscript/interscript-api/pull/16/files#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34R26

@phuonghuynh can you help with AWS part?

### CODE REVIEW

**Comment by phuonghuynh** [comment]
Yes @CAMOBAP

**Comment by phuonghuynh** [comment]
@ronaldtse GHA 

GHA PR is ready for preview, we need to add new secrets:
  - `GITHUB_PUSH_TOKEN`: GitHub token that has permission to push tags to the repository, this is required to trigger "release workflow", since existing `{{secrets.GITHUB_TOKEN}}` doesn't allow to invoke other workflows in GHA

working test projects can be found in my GH, "testci2", and "testci3" for reference.

Remaining issues:
- Update infra code to use "Release assets" from this repo
- Add GHA to infra repo to allow auto publish to aws lambda

**Comment by phuonghuynh** [comment]
Updated commit https://github.com/interscript/interscript-api/pull/16/commits/fbe8b287d6c9ff37b566b55ef244e32bc43b05ce using "INTERSCRIPT_CI_PAT" which might be available already, but we need someone who has permission to check it

**Comment by phuonghuynh** [comment]
ping @ronaldtse

**Review by ronaldtse — APPROVED** [review]

**Pull request merged**
