### PR TITLE
Feat: auto deploy aws

### PR DESCRIPTION
**Pull request by phuonghuynh**
Support auto release [-api](https://github.com/interscript/interscript-api) and aws-lambda [-aws-lambda](https://github.com/interscript/infrastructure)

Workflow:
1. Manual create a new GitHub Release new gem from [interscript repo](https://github.com/interscript/interscript)
2. (GHA) Auto dispatch the build an publish new GitHub Release for [-api](https://github.com/interscript/interscript-api), same version as the gem
3.  (GHA) Auto dispatch [-infrastructure](https://github.com/interscript/infrastructure) to deploy to aws lambda and push .statefile to github, all process should be done successfully. A new Pull Request is created and assigned to predefined [`.pr_reviewers`](https://github.com/interscript/infrastructure/blob/feat-auto-deploy-aws/.github/.pr_reviewers) to approve statefile changed and manual merge to master branch of  [-infrastructure](https://github.com/interscript/infrastructure)

Secrets variable required:
1. (might be done) Push permission token: `INTERSCRIPT_CI_PAT` in [-api](https://github.com/interscript/interscript-api) and [-infrastructure](https://github.com/interscript/infrastructure)
2. [-infrastructure](https://github.com/interscript/infrastructure): `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`
3. [`.pr_reviewers`](https://github.com/interscript/infrastructure/blob/feat-auto-deploy-aws/.github/.pr_reviewers): static csv string Reviewers assigned when Pull Request sent in [-infrastructure](https://github.com/interscript/infrastructure) after applying AWS Lambda successfully.

Related issue #12, #15, #3

### CODE REVIEW

**Comment by phuonghuynh** [comment]
PR https://github.com/interscript/infrastructure/pull/7 need to be merged also to enable this process.

**Comment by ronaldtse** [comment]
> Secrets variable required:
> 
> 1. (might be done) Push permission token: `INTERSCRIPT_CI_PAT` in [-api](https://github.com/interscript/interscript-api) and [-infrastructure](https://github.com/interscript/infrastructure)

Done. 

> 2. [-infrastructure](https://github.com/interscript/infrastructure): `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`

What kind of permissions does this account need? I've now put in the website deployment user.

Free free to merge when ready.

**Comment by phuonghuynh** [comment]
I think only [AWSLambda_FullAccess](https://console.aws.amazon.com/iam/home?region=us-east-1#/policies/arn%3Aaws%3Aiam%3A%3Aaws%3Apolicy%2FAWSLambda_FullAccess)

XRay will be removed in PR https://github.com/interscript/infrastructure/pull/8

**Comment by ronaldtse** [comment]
@phuonghuynh can you let me know if anything fails? We might need to setup a new AWS account for this.

**Comment by phuonghuynh** [comment]
PR to fix wrong git repository name merged, https://github.com/interscript/infrastructure/pull/9

@ronaldtse Auto workflow should work now, could you give it a try?

**Comment by phuonghuynh** [comment]
> We might need to setup a new AWS account for this.

yes, a deploy-account needed as we restrict to `allowed_account_ids = ["458282504429"]`
for now, we can set ` AWSLambda_FullAccess` is enough, as described in the [document](https://docs.aws.amazon.com/lambda/latest/dg/lambda-permissions.html)

> A Lambda function also has a policy, called an execution role, that grants it permission to access AWS services and resources. At a minimum, your function needs access to Amazon CloudWatch Logs for log streaming.

**Comment by phuonghuynh** [comment]
@ronaldtse after setting up AWS account, a manual release (push tag) on [interscript](https://github.com/interscript/interscript/blob/master/.github/workflows/release.yml#L6) is required to trigger this workflow as detailed in the [description section](https://github.com/interscript/interscript-api/pull/18#issue-533395351)

**Comment by ronaldtse** [comment]
@phuonghuynh can you help setup the new account and also make the deploy work? Thanks!

**Pull request merged**
